apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels:
    {{- include "myapp.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "myapp.selectorLabels" . | nindent 8 }}
      annotations:
        vault.security.banzaicloud.io/vault-addr: "https://vault.config:8200"
        vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
        vault.security.banzaicloud.io/vault-role: "admin"
        vault.security.banzaicloud.io/vault-serviceaccount: "atlantis"
        vault.security.banzaicloud.io/vault-path: "kubernetes"
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: atlantis
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - name: MYSECRET
            value: "<path:secret/data/shared/dev/testme-isnyder#foo>"
          #- name: MYSECRET
          #  valueFrom:
          #    secretKeyRef:
          #      name: {{ include "myapp.fullname" . }}-secret
          #      key: MYSECRET
          command:
            - /bin/bash
            - -c
            - "watch 'echo MYSECRET: $MYSECRET'"
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: nicolaka/netshoot:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
